:PROPERTIES:
:ID:       6ad28cee-dd57-409c-ad04-092987a7b54e
:END:
#+title: Recipe
#+filetags: :recipe:

* Creamy Chicken and Chorizo
:PROPERTIES:
:ID:       34c6c8ea-0d52-40e4-8456-1ef6e83347a6
:END:
** Ingredients
- bonless chicken thighs 1.3lb (600g)
- Spice mix
  - Smoked Paprika 1.5 tsp
  - Dried Oregano 1 tsp
  - Garlic Powder 1 tsp
  - Onion Powder 1 tsp
  - Salt + Pepper to taste
  - Cayanne Pepper 1/4 tsp
- Chroizo (100g)
- Garlic 2 cloves
- Dry White Wine 1/4 cup (60ml)
- Chicken Stock 3/4 cup (180ml)
- Heavy Cream 3/4 cup (180ml)
- Grated Parmesan 1/4 cup (20g)
- Fresh Basil (1/2 bunch)
- Cherry Tomatoes 175g (6oz)

** Instructions
*** Season and cook the chicken thighs
- Coat both sides of the chicken thighs with the seasoning.
- Add the oil to a large pan over medium-high heat.
- Once hot, add the thighs and fry both sides until lightly charred and cooked right through the centre (4-5 minutes on each side depending on size).
- Remove and place on a plate to one side. Lower the heat to medium.

*** During this time finely dice the onion and garlic, then halve the tomatoes and roughly dice the basil.
- If you need to grate the parmesan, make the stock and dice the chorizo do this now too, although if you run out of time you can do this whilst the onion is frying (next step).

*** Add the onion to the leftover fat in the pan and fry until it begins to soften.
- Add the chorizo and fry for 2 minutes, then add the garlic and fry for 30 seconds.
- Pour in the wine then raise the heat and bring to a rapid simmer. Cook for around 2 minutes until it almost completely evaporates. Lower the heat slightly.

*** Add the stock, cream and parmesan and give it a really good stir to blend everything.
- Simmer fairly rapidly for 3-4 minutes until the sauce thickens, stirring frequently.
- Add the tomatoes, basil and the resting juices from the chicken and gently simmer for a couple of minutes until the tomatoes begin to soften.

*** Turn the heat to low, add the chicken back and spoon over the sauce for a minute or so to warm it through. Serve and enjoy!


* Lemon Pepper Chicken Orzo
** Ingredients
- [ ] chicken thighs or breasts
- [ ] extra virgin olive oil
- [ ] plain Greek yogurt
- [ ] lemon juice
- [ ] dijon mustard
- [ ] garlic
- [ ] dried thyme
- [ ] paprika
- [ ] onion powder
- [ ] black pepper and salt
- [ ] bacon – if you don’t eat pork, omit this! Not a big deal at all, make this work best for you
- [ ] salted butter
- [ ] orzo pasta
- [ ] broccoli florets
- [ ] fresh basil and dill
** Ingredients – for the feta sauce
- [ ] feta cheese
- [ ] plain Greek Yogurt
- [ ] garlic
- [ ] lemon juice
- [ ] smoked paprika and chili flakes
** Instructions

*** Step 1: marinate the chicken
The Greek yogurt marinade makes all the difference. Marinate it in olive oil and yogurt with lemon, dijon, pepper, and garlic. Then add dried thyme and paprika and season with pepper and salt.

If time allows, marinate the chicken for 30 minutes or overnight. If you’re in a time crunch, just start cooking. I’ve now made this both ways; it is honestly great either way.

*** Step 2: start cooking
When you’re ready, start searing the chicken in an oven-safe cast iron skillet. Once it’s seared on both sides, you can remove it from the pan.

Add the bacon and get it nice and crispy all over. Now add some butter and some orzo. Let the orzo get toasty in the butter, then mix in water.

*** Step 3: baking
Stir in the broccoli. You could also use kale or even spinach. Then slide the chicken into the orzo and throw the whole skillet into the oven to finish cooking.

*** Step 4: the feta sauce
In my eyes, the feta sauce is the secret “sauce” to this dish.

It’s whipped feta cheese with a bit of yogurt and lemon, and if you have some fresh herbs on hand, toss those in too.

The salty feta creates an addicting sauce. Every spoonful is delicious and adds the best flavor to the peppery chicken.

*** Step 5: serving
When you pull the dish out of the oven, the sauce should have reduced, but the broccoli will be just perfectly cooked.

Add spoonfuls of the feta sauce, then fresh dill or basil.

Add some [5 ingredient beer bread](https://www.halfbakedharvest.com/5-ingredient-beer-bread/) to really complete this Gerard Family staple dinner. A comfort meal at its best! And the bacon is such a nice addition!


* Mongolian Beef Ramen
** Ingredients
- [ ] *3* packages instant ramen, flavor pack discarded
- [ ] *2* *Tbsp.* vegetable oil
- [ ] *1* *lb.* sirloin steak, sliced against the grain
- [ ] *2* *Tbsp.* cornstarch
- [ ] *1* *Tbsp.* toasted sesame oil
- [ ] *3* cloves garlic, minced
- [ ] *1* *tsp.* minced ginger
- [ ] *1/2* *cup* reduced-sodium soy sauce
- [ ] *1/4* *cup* lightly packed brown sugar
- [ ] *1* *cup* low-sodium chicken (or beef) broth
- [ ] Pinch red pepper flakes
- [ ] *1* large head broccoli, cut into florets
- [ ] *1* carrot, peeled and cut into matchsticks
- [ ] *3* scallions, thinly sliced
- [ ] Toasted sesame seeds, for garnish
** Directions
1. Cook ramen noodles according to package instructions. Drain and set aside.
2. In a large skillet over medium-high heat, heat oil. Toss beef with cornstarch. Add to skillet and cook until seared about 2 minutes per side. Transfer to a plate.
3. Reduce heat to medium-low. Add sesame oil to skillet and stir in garlic and ginger. Cook until fragrant, 1 minute then add soy sauce, brown sugar, and broth. Bring mixture to a boil, reduce heat and simmer until the sauce is thickened, 3 to 5 minutes.
4. Add broccoli and carrots then cover the skillet with a tight-fitting lid and cook until the vegetables are tender, about 5 minutes.
5. Return beef to skillet and stir until completely coated in sauce. Stir in cooked ramen noodles and scallions.
6. Garnish with toasted sesame seeds before serving.


* Roasted Garlic and Parmesan Chicken
** Ingredients
- chicken 1.5 lbs
- olive oil
- parmesan grated
- lemon juice + zest
- salt + pepper
- paprika
- italian seasoning
- parsley
- garlic head
- light mayo
** Instructions
- In a small saucepan over medium heat combine flour, milk, and water. Whisk together until smooth it thickens. Remove from heat and allow the Tangzhong to cool to room temperature while you prepare the rest of the dough.
- In a small bowl, combine the warm milk and 1 tbsp sugar. Sprinkle the yeast over the milk mixture and stir gently to dissolve. Let it sit for 5-10 minutes until it becomes frothy.
- In a large mixing bowl, combine the Tangzhong (cooled to room temperature), the yeast mixture, sugar, egg and egg yolk. Mix to combine.
- Gradually add in flour, a little at a time, until a dough starts to form and add salt. You may need a bit more flour depending on the humidity, but the dough should be soft and slightly sticky.
- Turn the dough out onto a lightly floured surface and knead for 8-10 minutes, or until the dough is smooth, elastic, and no longer sticky. Adding 1 tbsp of softened butter at a time until fully combined and elastic. You can also knead using a stand mixer with a dough hook for about 6-7 minutes. (Making sure it passes window pane test)
- Shape the dough into a ball and place it in a lightly greased bowl. Cover with a damp kitchen towel or plastic wrap. Allow the dough to rise in a warm place for about 1-1.5 hours, or until doubled in size.
- Once the dough has risen, punch it down to release the air. Turn the dough out onto a floured surface.
- Divide the dough into 12 equal pieces. (90g each) Roll each piece into a smooth ball, tucking the edges underneath.
- Arrange the dough balls in a greased 9x13-inch baking dish or round pan, placing them close together so they will bake into soft, pull-apart rolls. Cover the pan with a clean kitchen towel and let the rolls rise for 30-45 minutes, or until puffy and nearly doubled in size. Brush with egg wash before baking
- Preheat your oven to 375°F (190°C).
- Bake the rolls for 18-20 minutes, or until golden brown on top
- While the rolls are baking, prepare the honey butter by mixing the melted butter, honey, in a small bowl. Melt and mix until well combined
- Once the rolls are out of the oven, immediately brush them with the honey butter mixture for a sweet, glossy finish. Add coarse or sea salt and enjoy!nstructions
*** Marinate Chicken
- to chicken cubes add olive oil, paremesan, lemon juice + zest, salt + pepper, paprika, italian seasoning
*** Season and bake garlic bulb
- chopp end of garlic bulb
- add olive oil, salt, pepper, italian seasoning to garlic bulb
- pop bulb into oven at 350 for about 20 mins with seasoned chicken
*** Make Parmesan Sauce
- in a bowl add olive oil, parsley, parmesan, light mayo, roasted garlic, and cooked chicken juice from pan
- toss chicken in sauce and serve!


* White Chicken Chili
** Ingredients:
- Chicken Thighs- 3lbs
- Salt- 1tbsp
- Pepper- 1tbsp
- Cumin- 1tsp
- Garlic Powder- 1tbsp
- Onion Powder- 1tbsp
- Chili Powder- 2 1/2tbsp
- Oregano- 1tbsp
- Complete Seasoning- 2tbsp
- Smoked Paprika- 1tbsp
- Adobo Seasoning- 1tbsp
- Onions- 1 Half
- Green Peppers- 1
- Celery- 2
- Garlic- 3 cloves
- Green Chiles- 4oz
- Chopped Pickled Jalapeno- 4oz
- Cream Cheese- 8oz block
- Chicken Stock- 6 1/4 cups
- Heavy Cream- 1/2 cup
- Great Northern White Beans-2 15oz cans (1 can
blended, 1 whole)
- Black Beans- 8oz
** Instructions:
*** Make your seasoning blend and marinate the
chicken thighs with only half of it.
*** Chop an onion, bell pepper, celery, and garlic and
set aside.
*** Heat olive oil in a pot over medium-high heat and
sear the marinated chicken on each side until
browned but not fully cooked, then set it aside.
*** Add the chopped veggies to the pot and sauté until
fragrant. Deglaze with a splash of chicken broth,
scraping up the browned bits. Cook until the
veggies turn translucent.
*** Pour in enough chicken broth to cover the veggies
and bring to a simmer.
*** Add softened cream cheese, stirring until it melts
and creates a creamy base.
*** Return the chicken to the pot along with more broth
to cover, then cover and cook for 20 minutes.
*** Take the chicken out, shred it, and add it back in
with the rest of your seasoning blend, pureed and
whole white beans, black beans, corn, green chiles,
and pickled jalapeño.
*** Stir in a little heavy cream and simmer for about 45
minutes until thick and creamy.
*** Serve with Monterey Jack cheese, cilantro, fresh
jalapeños, lime wedges, sour cream, and Fritos for
the perfect finish.


* Bread (Dutch Oven)
** ingredients
- packet of yeast
- water 1.5 cups
- sugar 2 tsp
- salt 2 tsp
- butter 2 tbsp
- bread flour 420g @@comment: next time try 500g @@
** Instructions
*** activate yeast
 - by adding yeast, sugar, and the warm water to a bowl and let the yeast activate for about 5-10 mins
*** melt butter and add flour
- melt the butter in the microwave
- add flour and mix in the butter
*** incorporate ingredients
- use mixer on medium for about 7 mins
*** let bread rest for an hour
- while bread is resting preheat overn to 450
- once preheated put in dutch oven to heat for about 30 mins
*** form bread to a ball add parchment and place in dutch oven
- bake for about 30 mins
- take out and oncover and bake for another 10 mins to brown
** review
- the bread was still too sticky like 420g was not enough bread flower for 1.5 cups of water
- I tried 480g of flour this time and it might have been too much for the amount of water. I need to measure the water next time in ml
- add the butter right before kneading


* Texas Roadhouse Rolls
** Ingredients
- 585g bread flour (4 1/2 cups)
- 70g cup granulated sugar (1/3 cup)
- 3g salt (1/2 tsp)
- 10g active dry yeast (2 3/4 tsp)
- 245ml Whole milk (1 cup)
- 1 egg
- 1 egg yolk
- 57g butter, softened (1/4 cup, 4 tbsp)
- Tangzhong paste
*** Tangzhong paste
- 60g water (4 tbsp)
- 61g milk (4 tbsp)
- 18g bread flour (2 tbsp)
*** Honey butter
- 57g unsalted butter, melted (1/4 cup)
** Instructions
1) In a small *saucepan over medium heat combine flour (18g), milk (61g), and water (60g)*. Whisk together until smooth it thickens. Remove from heat and *allow the Tangzhong to cool* to room temperature while you prepare the rest of the dough.
2) In a small bowl, combine the *warm milk (425ml)* and *1 tbsp sugar*. Sprinkle the *yeast* over the milk mixture and stir gently to dissolve. Let it sit for *5-10 minutes* until it becomes frothy.
3) In a large mixing bowl, combine the Tangzhong (cooled to room temperature), the yeast mixture, sugar, *egg and egg yolk*. Mix to combine.
4) Gradually add in flour, a little at a time, until a dough starts to form and add salt. You may need a bit more flour depending on the humidity, but the dough should be soft and slightly sticky.
5) Turn the dough out onto a lightly floured surface and knead for 8-10 minutes, or until the dough is smooth, elastic, and no longer sticky. Adding 1 tbsp of softened butter at a time until fully combined and elastic. You can also knead using a stand mixer with a dough hook for about 6-7 minutes. (Making sure it passes window pane test)
6) Shape the dough into a ball and place it in a lightly greased bowl. Cover with a damp kitchen towel or plastic wrap. Allow the dough to rise in a warm place for about 1-1.5 hours, or until doubled in size.
7) Once the dough has risen, punch it down to release the air. Turn the dough out onto a floured surface.
8) Divide the dough into 12 equal pieces. (90g each) Roll each piece into a smooth ball, tucking the edges underneath.
9) Arrange the dough balls in a greased 9x13-inch baking dish or round pan, placing them close together so they will bake into soft, pull-apart rolls. Cover the pan with a clean kitchen towel and let the rolls rise for 30-45 minutes, or until puffy and nearly doubled in size. Brush with egg wash before baking
10) Preheat your oven to 375°F (190°C).
11) Bake the rolls for 18-20 minutes, or until golden brown on top
12) While the rolls are baking, prepare the honey butter by mixing the melted butter, honey, in a small bowl. Melt and mix until well combined
13) Once the rolls are out of the oven, immediately brush them with the honey butter mixture for a sweet, glossy finish. Add coarse or sea salt and enjoy!


* Honey Roasted Carrots
** Ingredients
- 2 pounds thin/baby carrots peeled, tops chopped off or to 2 inches*
- 1/4 cup apricot preserves
- 2 tablespoons honey
- 2 tablespoons olive oil
- 1 tablespoon butter, melted
- 1 tablespoon balsamic vinegar
- 3/4 tsp EACH McCormick® Garlic Powder, Salt
- 1/4 tsp EACH McCormick® Thyme Leaves, Pepper
- 1/8 tsp EACH McCormick® Ground Mustard, Cumin

** Instructions
- Preheat oven to 400 degrees F. Line a baking sheet with foil and lightly spray with nonstick cooking spray. Add carrots to the center of the pan. Set aside.
- In a medium bowl, whisk together all remaining ingredients and pour over the carrots. Toss until evenly coated. Line carrots in a single layer.
- Bake for 35-45 minutes at 400 degrees F depending on carrot thickness, until fork tender, stirring after 20 minutes.*** Roast longer for more caramelization. Garnish with fresh parsley if desired.


* Chicken & Red Pepper Pesto Sandwich
Serves 2 + left over pesto.

** Ingredients

*** Crispy Chicken & Assembly:
- [ ] 3-4 boneless skin-on chicken thighs
- [ ] Dried basil
- [ ] Salt/pepper
- [ ] 4 Sourdough slices
- [ ] Arugula
- [ ] Provolone cheese
*** Caramelised Onions:
- [ ] 1/2 tbsp Extra Virgin Olive Oil (EVOO)
- [ ] 2 red onions, thinly sliced
- [ ] 1 1/2 tbsp brown sugar
- [ ] 2 tsp apple cider vinegar
